export const SITUATION_LABELS = {
  RFI: "You're Raising First",
  "RFI EP/MP": "Facing raise at Early/Middle Position",
  "RFI CO": "Facing raise at Cutoff",
  "RFI BTN": "Facing raise at Button",
  "RFI SB": "Facing raise at Small Blind",
  "RFI BB": "Facing raise at Big Blind",
  "UTG vs 3Bet": "Facing 3-Bet at UTG",
  "UTG+1 vs 3Bet": "Facing 3-Bet at UTG+1",
  "UTG+2 vs 3Bet": "Facing 3-Bet at UTG+2",
  "LJ vs 3Bet": "Facing 3-Bet at Lojack",
  "HJ/CO vs 3Bet": "Facing 3-Bet at Hijact/Cutoff",
  "BTN/SB vs 3Bet": "Facing 3-Bet at Button/Small Blind",
};

export const POSITION_LABELS = {
  UTG: "From UTG",
  "UTG+1": "From UTG+1",
  "UTG+2": "From UTG+2",
  LJ: "From Lojack",
  HJ: "From Hijack",
  CO: "From Cutoff",
  BTN: "From Button",
  SB: "From SB",

  "UTG+1 vs UTG": "You're UTG+1, facing raise from UTG",
  "UTG+2 vs UTG/UTG+1": "You're UTG+2 facing raise from UTG/UTG+1",
  "LJ vs UTG/UTG+1": "You're Lojack facing raise from UTG/UTG+1",
  "LJ vs UTG+2": "You're Lojack facing raise from UTG+2",
  "HJ vs UTG": "You're Hijack facing raise from UTG",
  "HJ vs UTG+1": "You're Hijack facing raise from UTG+1",
  "HJ vs UTG+2": "You're Hijack facing raise from UTG+2",
  "HJ vs LJ": "You're Hijack facing raise from Lojack",

  "CO vs UTG/UTG+1": "From UTG/UTG+1 - CO",
  "CO vs UTG+2": "From UTG+2 - CO",
  "CO vs LJ": "From Lojack - CO",
  "CO vs HJ": "From Hijack - CO",

  "BTN vs UTG": "From UTG - BTN",
  "BTN vs UTG+1": "From UTG+1 - BTN",
  "BTN vs UTG+2": "From UTG+2 - BTN",
  "BTN vs LJ": "From Lojack - BTN",
  "BTN vs HJ": "From Hijack - BTN",
  "BTN vs CO": "From Cutoff - BTN",

  "SB vs UTG/UTG+1": "From UTG/UTG+1 - SB",
  "SB vs UTG+2": "From UTG+2 - SB",
  "SB vs LJ": "From Lojack - SB",
  "SB vs HJ": "From Hijack - SB",
  "SB vs CO": "From Cutoff - SB",
  "SB vs BTN": "From Button - SB",

  "BB vs UTG/UTG+1": "From UTG/UTG+1 - BB",
  "BB vs UTG+2": "From UTG+2 - BB",
  "BB vs LJ": "From Lojack - BB",
  "BB vs HJ": "From Hijack - BB",
  "BB vs CO": "From Cutoff - BB",
  "BB vs BTN": "From Button - BB",
  "BB vs SB": "From Small Blind - BB",

  "UTG vs UTG+1": "From UTG+1 - UTG",
  "UTG vs UTG+2": "From UTG+2 - UTG",
  "UTG vs LJ": "From Lojack - UTG",
  "UTG vs HJ": "From Hijack - UTG",
  "UTG vs CO/BTN": "From Cutoff/Button - UTG",
  "UTG vs SB/BB": "From Blinds - UTG",

  "UTG+1 vs UTG+2": "From UTG+2 - UTG1",
  "UTG+1 vs LJ": "From Lojack - UTG1",
  "UTG+1 vs HJ/CO": "From Hijack/Cutoff - UTG1",
  "UTG+1 vs BTN": "From Button - UTG1",
  "UTG+1 vs SB/BB": "From Blinds - UTG1",

  "UTG+2 vs LJ": "From Lojack - UTG2",
  "UTG+2 vs HJ": "From Hijack - UTG2",
  "UTG+2 vs CO/BTN": "From Cutoff/Button - UTG2",
  "UTG+2 vs SB/BB": "From Blinds - UTG2",

  "LJ vs HJ": "From Hijack - LJ",
  "LJ vs CO": "From Cutoff - LJ",
  "LJ vs BTN": "From Button - LJ",
  "LJ vs SB": "From Small Blind - LJ",
  "LJ vs BB": "From Big Blind - LJ",

  "HJ vs CO": "From Cutoff - HJ",
  "HJ vs BTN": "From Button - HJ",
  "HJ vs SB": "From Small Blind - HJ",
  "HJ vs BB": "From Big Blind - HJ",
  "HJ vs BTN/SB": "From Button/Small Blind - HJ",
  "CO vs BB": "From Big Blind - CO",

  "BTN vs SB/BB": "At Button From Blinds",
  "SB RFI vs BB": "At SB(RFI) From Big Blind",
  "SB Limp vs BB": "At SB(Limp) From Big BLind",
};

export const getLabel = (dict, key) => dict[key] || key;
