export const SITUATION_LABELS = {
  RFI: "You're Raising First",
  "RFI EP/MP": "Facing raise at Early/Middle Position",
  "RFI CO": "Facing raise at Cutoff",
  "RFI BTN": "Facing raise at Button",
  "RFI SB": "Facing raise at Small Blind",
  "RFI BB": "Facing raise at Big Blind",
  "UTG vs 3Bet": "Facing 3-Bet at UTG",
  "UTG+1 vs 3Bet": "Facing 3-Bet at UTG+1",
  "UTG+2 vs 3Bet": "Facing 3-Bet at UTG+2",
  "LJ vs 3Bet": "Facing 3-Bet at Lojack",
  "HJ/CO vs 3Bet": "Facing 3-Bet at Hijact/Cutoff",
  "BTN/SB vs 3Bet": "Facing 3-Bet at Button/Small Blind",
};

export const POSITION_LABELS = {
  UTG: "From UTG",
  "UTG+1": "From UTG+1",
  "UTG+2": "From UTG+2",
  LJ: "From Lojack",
  HJ: "From Hijack",
  CO: "From Cutoff",
  BTN: "From Button",
  SB: "From SB",

  "UTG+1 vs UTG": "You're UTG+1, facing raise from UTG",
  "UTG+2 vs UTG/UTG+1": "You're UTG+2 facing raise from UTG/UTG+1",
  "LJ vs UTG/UTG+1": "You're Lojack facing raise from UTG/UTG+1",
  "LJ vs UTG+2": "You're Lojack facing raise from UTG+2",
  "HJ vs UTG": "You're Hijack facing raise from UTG",
  "HJ vs UTG+1": "You're Hijack facing raise from UTG+1",
  "HJ vs UTG+2": "You're Hijack facing raise from UTG+2",
  "HJ vs LJ": "You're Hijack facing raise from Lojack",

  "CO vs UTG/UTG+1": "From UTG/UTG+1",
  "CO vs UTG+2": "From UTG+2",
  "CO vs LJ": "From Lojack",
  "CO vs HJ": "From Hijack",

  "BTN vs UTG": "From UTG",
  "BTN vs UTG+1": "From UTG+1",
  "BTN vs UTG+2": "From UTG+2",
  "BTN vs LJ": "From Lojack",
  "BTN vs HJ": "From Hijack",
  "BTN vs CO": "From Cutoff",

  "SB vs UTG/UTG+1": "From UTG/UTG+1",
  "SB vs UTG+2": "From UTG+2",
  "SB vs LJ": "From Lojack",
  "SB vs HJ": "From Hijack",
  "SB vs CO": "From Cutoff",
  "SB vs BTN": "From Button",

  "BB vs UTG/UTG+1": "From UTG/UTG+1",
  "BB vs UTG+2": "From UTG+2",
  "BB vs LJ": "From Lojack",
  "BB vs HJ": "From Hijack",
  "BB vs CO": "From Cutoff",
  "BB vs BTN": "From Button",
  "BB vs SB": "From Small Blind",

  "UTG vs UTG+1": "From UTG+1",
  "UTG vs UTG+2": "From UTG+2",
  "UTG vs LJ": "From Lojack",
  "UTG vs HJ": "From Hijack",
  "UTG vs CO/BTN": "From Cutoff/Button",
  "UTG vs SB/BB": "From Blinds",

  "UTG+1 vs UTG+2": "From UTG+2",
  "UTG+1 vs LJ": "From Lojack",
  "UTG+1 vs HJ/CO": "From Hijack/Cutoff",
  "UTG+1 vs BTN": "From Button",
  "UTG+1 vs SB/BB": "From Blinds",

  "UTG+2 vs LJ": "From Lojack",
  "UTG+2 vs HJ": "From Hijack",
  "UTG+2 vs CO/BTN": "From Cutoff/Button",
  "UTG+2 vs SB/BB": "From Blinds",

  "LJ vs HJ": "From Hijack",
  "LJ vs CO": "From Cutoff",
  "LJ vs BTN": "From Button",
  "LJ vs SB": "From Small Blind",
  "LJ vs BB": "From Big Blind",

  "HJ vs CO": "From Cutoff",
  "HJ vs BTN": "From Button",
  "HJ vs SB": "From Small Blind",
  "HJ vs BB": "From Big Blind",
  "HJ vs BTN/SB": "From Button/Small Blind",
  "CO vs BB": "From Big Blind",

  "BTN vs SB/BB": "At Button From Blinds",
  "SB RFI vs BB": "At SB(RFI) From Big Blind",
  "SB Limp vs BB": "At SB(Limp) From Big BLind",
};

export const getLabel = (dict, key) => dict[key] || key;
